## Importing the Libraries

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.7.0'

## Part 1 : Data Preprocessing

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [8]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
X = dataset.iloc[:,3:-1]
y = dataset.iloc[:,-1]

In [12]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [13]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [15]:
X = X.values
y = y.values

In [16]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [18]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

## Part2 : Encoding Categorical Data

### Label Encoding for 'Gender' Column

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le = LabelEncoder()

In [23]:
le.fit_transform(X[:,2])

array([0, 0, 0, ..., 0, 1, 0])

In [24]:
X[:,2] = le.fit_transform(X[:,2])

In [25]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [26]:
2 > 1

True

### One Hot Encoding for 'Geoghraphy' Column

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [33]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')

In [46]:
ct.fit_transform(X)

array([[1.0, 0.0, 1.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 1.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 1.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 1.0, ..., 1, 0, 38190.78]], dtype=object)

In [47]:
ct.fit_transform(X)[0]

array([1.0, 0.0, 1.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [43]:
X = ct.fit_transform(X)

In [44]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [48]:
type(X)

numpy.ndarray

## Part3 : Splitting the Data

### Splitting the Data set into Training set and Test set

In [53]:
from sklearn.model_selection import train_test_split

In [147]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [148]:
X_train

array([[0.0, 0.0, 1.0, ..., 1, 0, 163830.64],
       [0.0, 1.0, 0.0, ..., 1, 1, 57098.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

In [149]:
X_test

array([[0.0, 1.0, 0.0, ..., 1, 1, 192852.67],
       [1.0, 0.0, 0.0, ..., 1, 0, 128702.1],
       [0.0, 0.0, 1.0, ..., 1, 1, 75732.25],
       ...,
       [0.0, 0.0, 1.0, ..., 1, 0, 141533.19],
       [0.0, 1.0, 0.0, ..., 1, 1, 11276.48],
       [0.0, 1.0, 0.0, ..., 1, 0, 192950.6]], dtype=object)

In [151]:
len(y_train)

8000

In [150]:
len(y_test)

2000

## Part4 : Scale the Features

### Feature Scaling

In [153]:
from sklearn.preprocessing import StandardScaler

In [154]:
sc = StandardScaler()

In [155]:
X_train

array([[0.0, 0.0, 1.0, ..., 1, 0, 163830.64],
       [0.0, 1.0, 0.0, ..., 1, 1, 57098.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

In [156]:
sc.fit_transform(X_train)

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [157]:
X_train = sc.fit_transform(X_train)

In [158]:
X_test = sc.transform(X_test)

In [159]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

## Part5 : Bulding the ANN

#### Initializing the Ann

In [160]:
ann = tf.keras.models.Sequential()

#### Adding the input Layer and First Hidden Layer

In [161]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

#### Adding the Second Hidden Layer

In [162]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

#### Adding the Output Layer

In [163]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Part6 : Training the ANN

#### Compile the ANN

In [164]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

#### Training the ANN on Training Set

In [165]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5782 - accuracy: 0.7625
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4676 - accuracy: 0.7914
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4291 - accuracy: 0.8036
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4336 - accuracy: 0.7997
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4099 - accuracy: 0.8196
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4154 - accuracy: 0.8176
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4178 - accuracy: 0.8145
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3982 - accuracy: 0.8241
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4115 - accuracy: 0.8187
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3986 - accura

In [78]:
32*250

8000

## Part7 : Making the Predictions and Evaluation the Model

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer ?

In [166]:
Mammad = [1 , 0 , 0 , 600 , 1 , 40 , 3 , 60000 , 2 , 1 , 1 , 50000]

In [167]:
sc.transform([Mammad])

array([[ 0.98560362, -0.5698444 , -0.57369368, -0.52111599,  0.91601335,
         0.10961719, -0.68538967, -0.2569057 ,  0.8095029 ,  0.64259497,
         0.9687384 , -0.87203322]])

In [168]:
Mammad = sc.transform([Mammad])

In [169]:
ann.predict(Mammad)

array([[0.06542048]], dtype=float32)

In [170]:
print(ann.predict(Mammad) > 0.5)

[[False]]


In [171]:
Hargrave = [[1,0,0,619,0,42,2,0.00,1,1,1,101348.88]]

In [172]:
Hargrave = sc.transform(Hargrave)

In [173]:
ann.predict(Hargrave)

array([[0.42981234]], dtype=float32)

In [174]:
print(ann.predict(Hargrave) > 0.5)

[[False]]


#### Predicting the Test set Result

In [175]:
# Will be Teached in Next Session